// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NETUA2_Egzaminas.DAL;

#nullable disable

namespace NETUA2_Egzaminas.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241009132608_updated_itemInstance2")]
    partial class updated_itemInstance2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.BaseStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Magic")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BaseStats");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.CharAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharId")
                        .HasColumnType("int");

                    b.Property<string>("DateOfCompletion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharId");

                    b.ToTable("CharAchievements");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.CharEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amulet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Armor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Boots")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gloves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Helmet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Legs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RingLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RingRight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shield")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weapon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CharEquipment");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.CharInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Slot10Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot11Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot12Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot13Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot14Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot15Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot16Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot17Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot18Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot19Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot20Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot21Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot22Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot23Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot24Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot25Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot26Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot27Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot28Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot2Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot3Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot4Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot5Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot6Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot7Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot8Id")
                        .HasColumnType("int");

                    b.Property<int?>("Slot9Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slot10Id");

                    b.HasIndex("Slot11Id");

                    b.HasIndex("Slot12Id");

                    b.HasIndex("Slot13Id");

                    b.HasIndex("Slot14Id");

                    b.HasIndex("Slot15Id");

                    b.HasIndex("Slot16Id");

                    b.HasIndex("Slot17Id");

                    b.HasIndex("Slot18Id");

                    b.HasIndex("Slot19Id");

                    b.HasIndex("Slot1Id");

                    b.HasIndex("Slot20Id");

                    b.HasIndex("Slot21Id");

                    b.HasIndex("Slot22Id");

                    b.HasIndex("Slot23Id");

                    b.HasIndex("Slot24Id");

                    b.HasIndex("Slot25Id");

                    b.HasIndex("Slot26Id");

                    b.HasIndex("Slot27Id");

                    b.HasIndex("Slot28Id");

                    b.HasIndex("Slot2Id");

                    b.HasIndex("Slot3Id");

                    b.HasIndex("Slot4Id");

                    b.HasIndex("Slot5Id");

                    b.HasIndex("Slot6Id");

                    b.HasIndex("Slot7Id");

                    b.HasIndex("Slot8Id");

                    b.HasIndex("Slot9Id");

                    b.ToTable("CharInventory");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.CharQuests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharId")
                        .HasColumnType("int");

                    b.Property<string>("DateOfCompletion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharId");

                    b.ToTable("CharQuests");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.CharSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Skill1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Skill2Id")
                        .HasColumnType("int");

                    b.Property<int?>("Skill3Id")
                        .HasColumnType("int");

                    b.Property<int?>("Skill4Id")
                        .HasColumnType("int");

                    b.Property<int?>("Skill5Id")
                        .HasColumnType("int");

                    b.Property<int?>("Skill6Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Skill1Id");

                    b.HasIndex("Skill2Id");

                    b.HasIndex("Skill3Id");

                    b.HasIndex("Skill4Id");

                    b.HasIndex("Skill5Id");

                    b.HasIndex("Skill6Id");

                    b.ToTable("CharSkills");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.Character", b =>
                {
                    b.Property<int>("CharId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharId"));

                    b.Property<int>("BaseStatsId")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillsId")
                        .HasColumnType("int");

                    b.Property<int>("StatsId")
                        .HasColumnType("int");

                    b.HasKey("CharId");

                    b.HasIndex("BaseStatsId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("SkillsId");

                    b.HasIndex("StatsId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("Attack")
                        .HasColumnType("int");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Durability")
                        .HasColumnType("int");

                    b.Property<string>("ImgId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Stackable")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.ItemInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Attack")
                        .HasColumnType("int");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Durability")
                        .HasColumnType("int");

                    b.Property<string>("ImgId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Stackable")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ItemInstances");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.ProfileImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageBytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProfileImages");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.SkillInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<double>("Xp")
                        .HasColumnType("float");

                    b.Property<int>("XpCap")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SkillInstances");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Magic")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterCharId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResidenceId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterCharId");

                    b.HasIndex("ImageId");

                    b.HasIndex("ResidenceId")
                        .IsUnique()
                        .HasFilter("[ResidenceId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UsersInfo");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.UserResidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersResidences");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.CharAchievement", b =>
                {
                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.Character", "Character")
                        .WithMany("AchievementsList")
                        .HasForeignKey("CharId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.CharInventory", b =>
                {
                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot10")
                        .WithMany()
                        .HasForeignKey("Slot10Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot11")
                        .WithMany()
                        .HasForeignKey("Slot11Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot12")
                        .WithMany()
                        .HasForeignKey("Slot12Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot13")
                        .WithMany()
                        .HasForeignKey("Slot13Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot14")
                        .WithMany()
                        .HasForeignKey("Slot14Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot15")
                        .WithMany()
                        .HasForeignKey("Slot15Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot16")
                        .WithMany()
                        .HasForeignKey("Slot16Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot17")
                        .WithMany()
                        .HasForeignKey("Slot17Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot18")
                        .WithMany()
                        .HasForeignKey("Slot18Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot19")
                        .WithMany()
                        .HasForeignKey("Slot19Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot1")
                        .WithMany()
                        .HasForeignKey("Slot1Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot20")
                        .WithMany()
                        .HasForeignKey("Slot20Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot21")
                        .WithMany()
                        .HasForeignKey("Slot21Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot22")
                        .WithMany()
                        .HasForeignKey("Slot22Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot23")
                        .WithMany()
                        .HasForeignKey("Slot23Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot24")
                        .WithMany()
                        .HasForeignKey("Slot24Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot25")
                        .WithMany()
                        .HasForeignKey("Slot25Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot26")
                        .WithMany()
                        .HasForeignKey("Slot26Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot27")
                        .WithMany()
                        .HasForeignKey("Slot27Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot28")
                        .WithMany()
                        .HasForeignKey("Slot28Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot2")
                        .WithMany()
                        .HasForeignKey("Slot2Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot3")
                        .WithMany()
                        .HasForeignKey("Slot3Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot4")
                        .WithMany()
                        .HasForeignKey("Slot4Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot5")
                        .WithMany()
                        .HasForeignKey("Slot5Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot6")
                        .WithMany()
                        .HasForeignKey("Slot6Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot7")
                        .WithMany()
                        .HasForeignKey("Slot7Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot8")
                        .WithMany()
                        .HasForeignKey("Slot8Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ItemInstance", "Slot9")
                        .WithMany()
                        .HasForeignKey("Slot9Id");

                    b.Navigation("Slot1");

                    b.Navigation("Slot10");

                    b.Navigation("Slot11");

                    b.Navigation("Slot12");

                    b.Navigation("Slot13");

                    b.Navigation("Slot14");

                    b.Navigation("Slot15");

                    b.Navigation("Slot16");

                    b.Navigation("Slot17");

                    b.Navigation("Slot18");

                    b.Navigation("Slot19");

                    b.Navigation("Slot2");

                    b.Navigation("Slot20");

                    b.Navigation("Slot21");

                    b.Navigation("Slot22");

                    b.Navigation("Slot23");

                    b.Navigation("Slot24");

                    b.Navigation("Slot25");

                    b.Navigation("Slot26");

                    b.Navigation("Slot27");

                    b.Navigation("Slot28");

                    b.Navigation("Slot3");

                    b.Navigation("Slot4");

                    b.Navigation("Slot5");

                    b.Navigation("Slot6");

                    b.Navigation("Slot7");

                    b.Navigation("Slot8");

                    b.Navigation("Slot9");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.CharQuests", b =>
                {
                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.Character", "Character")
                        .WithMany("Quests")
                        .HasForeignKey("CharId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.CharSkills", b =>
                {
                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.SkillInstance", "Woodcutting")
                        .WithMany()
                        .HasForeignKey("Skill1Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.SkillInstance", "Mining")
                        .WithMany()
                        .HasForeignKey("Skill2Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.SkillInstance", "Fishing")
                        .WithMany()
                        .HasForeignKey("Skill3Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.SkillInstance", "Cooking")
                        .WithMany()
                        .HasForeignKey("Skill4Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.SkillInstance", "Crafting")
                        .WithMany()
                        .HasForeignKey("Skill5Id");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.SkillInstance", "Smithing")
                        .WithMany()
                        .HasForeignKey("Skill6Id");

                    b.Navigation("Cooking");

                    b.Navigation("Crafting");

                    b.Navigation("Fishing");

                    b.Navigation("Mining");

                    b.Navigation("Smithing");

                    b.Navigation("Woodcutting");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.Character", b =>
                {
                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.BaseStats", "BaseStats")
                        .WithMany()
                        .HasForeignKey("BaseStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.CharEquipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.CharInventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.CharSkills", "Skills")
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.Stats", "Stats")
                        .WithMany()
                        .HasForeignKey("StatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseStats");

                    b.Navigation("Equipment");

                    b.Navigation("Inventory");

                    b.Navigation("Skills");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.UserInfo", b =>
                {
                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterCharId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.ProfileImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.UserResidence", "Residence")
                        .WithOne("UserInfo")
                        .HasForeignKey("NETUA2_Egzaminas.DAL.Entities.UserInfo", "ResidenceId");

                    b.HasOne("NETUA2_Egzaminas.DAL.Entities.User", null)
                        .WithOne("UserInfo")
                        .HasForeignKey("NETUA2_Egzaminas.DAL.Entities.UserInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Image");

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.Character", b =>
                {
                    b.Navigation("AchievementsList");

                    b.Navigation("Quests");
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.User", b =>
                {
                    b.Navigation("UserInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("NETUA2_Egzaminas.DAL.Entities.UserResidence", b =>
                {
                    b.Navigation("UserInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
